

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlInventory
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3316:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql