

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlnew
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql